//nolint
package config

// UPDATE SESSION EVERY NOW > THIRTY_MINUTES
const SESSION_REFRESH_TIMEOUT = THIRTY_MINUTES

// LOGOUT SESSSION WHEN NOW > SIX_HOURS
const SESSION_EXPIRE_TIMEOUT = SIX_HOURS

const REDIS_INIT_TTL = ONE_HOUR_IN_SECONDS
const REDIS_EXTEND_TTL = ONE_HOUR_IN_SECONDS
